### ISSUE TITLE
The packages are not available from current channels.

### ISSUE THREAD

**Issue by KF243** [elerac/optosigma#1] opened 2021-10-20 05:03 UTC
Hi Ryota,

I'm beginner for python-coding of GSC-01(OPTOSIGMA) controlling.
Your optosigma seems to be fantastic for my purpose. But my anaconda python fails to install it since the following messages are returned. The same message was found on the vanilla python. Could you tell me how I fix it. 

(biologic) C:\Users\kfush>conda install git+https://github.com/elerac/optosigma
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
PackagesNotFoundError: The following packages are not available from current channels:
  - //github.com/elerac/optosigma
Current channels:
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
To search for alternate channels that may provide the conda package you're
looking for, navigate to
    https://anaconda.org
and use the search bar at the top of the page.

**Comment by elerac** [comment] 2021-10-20 05:44
Hi @KF243 !

I don't support installing optosigma through `conda`. So, you must install via `pip`.

Try following commands.
```shell
pip install git+https://github.com/elerac/optosigma
```
or
```shell
pip install --no-deps git+https://github.com/elerac/optosigma
conda install -c anaconda pyserial
```

**Comment by KF243** [comment] 2021-10-20 10:00
Thanks for the response. After the installing git, optosigma was successfully installed on the vanilla python. Now I am coding an xy-scanner using two PAT-001 (predecessor of GSC-01). It seems going good.
However, optosigma could not be installed on the anaconda. If you would realize it, please tell me.

**Comment by elerac** [comment] 2021-10-20 10:45
Well..., it seems that the problem is caused by your (complex?) python environment. Make sure you use **anaconda's `pip`** (NOT vanilla python's pip).

I'm sorry, but I close this issue because the problem is not caused by optosigma.
But if you have another problem caused by optosigma, ask me again.

**Closed as completed** 2021-10-20 10:46 UTC
